apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.uniqueName}}
  description: ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: url:https://gitea-gitea.${{ values.clusterDomain }}/ws-${{ values.owner }}/${{ values.name }}/src/branch/main/
    backstage.io/source-location: url:https://gitea-gitea.${{ values.clusterDomain }}/ws-${{ values.owner }}/${{ values.name }}
    backstage.io/view-url: https://gitea-gitea.${{ values.clusterDomain }}/ws-${{ values.owner }}/${{ values.name }}
    backstage.io/kubernetes-id: ${{values.uniqueName}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    janus-idp.io/tekton: ${{values.uniqueName}}
    argocd/app-name: ${{values.uniqueName}}
    argocd/app-namespace: openshift-gitops
    tektonci/build-namespace: ${{values.namespace}}
    che.eclipse.org/che-server: https://devspaces.${{ values.clusterDomain }}
    devspaces.io/factory: "https://devspaces.${{ values.clusterDomain }}/#https://gitea-gitea.${{ values.clusterDomain }}/ws-${{ values.owner }}/${{ values.name }}.git?new"
  links:
    - url: "https://devspaces.${{ values.clusterDomain }}/#https://gitea-gitea.${{ values.clusterDomain }}/ws-${{ values.owner }}/${{ values.name }}.git?new"
      title: Open in DevSpaces
      icon: catalog
      type: ide
    - url: "https://gitea-gitea.${{ values.clusterDomain }}/ws-${{ values.owner }}/${{ values.name }}"
      title: View Source
      icon: github
      type: source
  tags:
    - frontend
    - html
    - neuralbank
spec:
  type: website
  lifecycle: experimental
  owner: user:${{values.owner}}
  system: ${{values.owner}}-neuralbank
  consumesApis:
    - ${{values.backendApiName | default(values.owner + '-neuralbank-backend-api') }}
  dependsOn:
    - component:default/${{values.backendUniqueName | default(values.owner + '-neuralbank-backend') }}
