schemaVersion: 2.2.2
metadata:
  name: ${{values.name}}
  version: 1.0.0
  displayName: ${{values.name}}
  description: ${{values.description}}
  language: HTML
  projectType: Static
projects:
  - name: ${{values.name}}
    git:
      remotes:
        origin: https://gitea-gitea.${{values.clusterDomain}}/ws-${{values.owner}}/${{values.name}}.git
      checkoutFrom:
        revision: main
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:latest
      memoryLimit: 1Gi
      cpuLimit: "1"
      mountSources: true
commands:
  - id: 01-serve
    exec:
      component: tools
      commandLine: python3 -m http.server 8080
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run
        isDefault: true
