{{- if .Values.clusterDomain }}
---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: workshop-dark-theme-hint
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  text: >-
    Red Hat Tech Day Chile
  location: BannerTop
  color: "#FFFFFF"
  backgroundColor: "#EE0000"
{{- end }}
