{{- if .Values.clusterDomain }}
---
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: workshop-dark-theme-hint
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  text: >-
    Red Hat Tech Day Santiago 🇨🇱
  location: BannerTop
  color: "#000000"
  backgroundColor: "#FDE3E4"
{{- end }}
