quarkus.http.port=8080

# DevSpaces / remote dev mode
%dev.quarkus.http.host=0.0.0.0
%dev.quarkus.http.proxy.proxy-address-forwarding=true
%dev.quarkus.dev-ui.hosts=^.*$
quarkus.container-image.build=true
quarkus.container-image.push=true
quarkus.container-image.registry=${{values.imageRegistry}}
quarkus.container-image.group=${{values.namespace}}
quarkus.container-image.name=${{values.name}}
quarkus.container-image.tag=latest
