apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    app.kubernetes.io/part-of: neuralbank
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{values.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{values.name}}
        backstage.io/kubernetes-id: ${{values.uniqueName}}
    spec:
      containers:
        - name: ${{values.name}}
          image: ${{values.imageRegistry}}/${{values.namespace}}/${{values.name}}:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
