apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ${{values.name}}-listener
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: ${{values.name}}-trigger-sa
  triggers:
    - name: gitea-push
      bindings:
        - kind: TriggerBinding
          ref: ${{values.name}}-binding
      template:
        ref: ${{values.name}}-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-${{values.name}}-listener
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: el-${{values.name}}-listener
    weight: 100
