apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ${{values.name}}-initial-build
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
    tekton.dev/pipeline: ${{values.name}}-build
spec:
  pipelineRef:
    name: ${{values.name}}-build
  params:
    - name: git-url
      value: http://gitea-http.gitea.svc.cluster.local:3000/ws-${{values.owner}}/${{values.name}}.git
    - name: git-revision
      value: main
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
