apiVersion: v1
kind: Service
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    backstage.io/kubernetes-id: ${{values.uniqueName}}
spec:
  selector:
    app.kubernetes.io/name: ${{values.name}}
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 8080
      targetPort: 8080
