apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ${{values.name}}-binding
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  params:
    - name: git-url
      value: http://gitea-http.gitea.svc.cluster.local:3000/$(body.repository.full_name).git
    - name: git-revision
      value: $(body.after)
