clusterDomain: ""
mavenMirror:
  namespace: maven-mirror
  name: maven-mirror
  image: docker.io/library/nginx:1.27-alpine
  replicaCount: 2
  cache:
    enabled: true
    storageClassName: ocs-external-storagecluster-cephfs
    size: 50Gi
