apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.uniqueName}}
  namespace: openshift-gitops
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/ws-${{values.owner}}/${{values.name}}.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
