apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${{values.uniqueName}}-pipeline-scc-privileged
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ${{values.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.name}}-trigger-sa
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.name}}-trigger-binding
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
subjects:
  - kind: ServiceAccount
    name: ${{values.name}}-trigger-sa
    namespace: ${{values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${{values.uniqueName}}-trigger-clusterbinding
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
subjects:
  - kind: ServiceAccount
    name: ${{values.name}}-trigger-sa
    namespace: ${{values.namespace}}
