apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    app.kubernetes.io/part-of: neuralbank
    app.openshift.io/runtime: quarkus
    backstage.io/kubernetes-id: ${{values.uniqueName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{values.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{values.name}}
        app.openshift.io/runtime: quarkus
        backstage.io/kubernetes-id: ${{values.uniqueName}}
    spec:
      containers:
        - name: ${{values.name}}
          image: ${{values.imageRegistry}}/${{values.namespace}}/${{values.name}}:latest
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
