apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ${{values.name}}-template
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.uniqueName}}
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ${{values.name}}-run-
        namespace: ${{values.namespace}}
        labels:
          backstage.io/kubernetes-id: ${{values.uniqueName}}
          tekton.dev/pipeline: ${{values.name}}-build
      spec:
        pipelineRef:
          name: ${{values.name}}-build
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: maven-settings
            emptyDir: {}
